### ISSUE TITLE
New API

### ISSUE THREAD

**Issue by Agent471** [encode32/PokeVisionFinder#13]
Can you add a 10 second delay after catching a pokemon according to new api please .
Because pokesniper2 had it in new update in its autosniper function.
It doesn't catch the pokemon right after catching a one .

**Comment by micreu** [comment]
![pokevison](https://cloud.githubusercontent.com/assets/9334191/17607739/fc30843e-6027-11e6-9a1e-e1fdc22db9ec.png)

**Comment by Agent471** [comment]
Thanks for your respond really appreciated!!!!
