### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Rhengar** [encode32/PokeVisionFinder#2]
The scanner works great! Just get '[ERROR] KeyError = 'pokemons' ' sometimes at certain cities.
How do I fix this? 

Thanks in advance

**Comment by encode32** [comment]
Its a common issue, the retieved information from the website is not correct so it throw that error.

**Comment by Rhengar** [comment]
Thanks for the quick answer.

**Comment by encode32** [comment]
No problem. i could have just not show any message but i preffer show the error message so you know that it happened, maybe i should add an option for showing that kind of error or not.
