### ISSUE TITLE
Arguments are messed up now.

### ISSUE THREAD

**Issue by theantihero** [encode32/PokeVisionFinder#5]
I can't run python ~/pokefinder/PokeVisionFinder.py dratini

throws error

PokeVisionFinder.py", line 198, in <module>
    _inputpoke = [line.strip() for line in open(argv[1], 'r')]
IOError: [Errno 2] No such file or directory: 'dratini'

I can run it with
python ~/pokefinder/PokeVisionFinder.py dratini,dratini

but theres issues with this. Doesn't search for dratinis, but looks for every type of pokemon. :/

Previous version is fine for me. Gonna downgrade.

**Comment by encode32** [comment]
Fixed on latest update, thanks for inform.
