### ISSUE TITLE
Not catching anything. Keeps logging in 

### ISSUE THREAD

**Issue by flo-security** [encode32/PokeVisionFinder#9]
![image](https://cloud.githubusercontent.com/assets/20738058/17361195/7d45bcb6-596f-11e6-927b-c65780ca679f.png)
Experiencing login problems, while Pokesniper2 V1.9 in standalone does login. Now I need to enter coords in manually to catch them in Pokesniper2 1.9. Any advice?

**Comment by sakiyako** [comment]
http://prntscr.com/c117nj
